#+title: README / User Guide
* Playing with Build_Spectra
** Background
The entrypoint function =handle= takes an =ApiRequest= as an input - it automatically figures out release info such as paths to files from this.

Here's an example of constructing a request
#+begin_src python
    params = TargetParameters(target_ids=targets)
    req = ApiRequest(
        command=Command.DOWNLOAD,
        request_type=RequestType.TARGETS,
        release="fuji",
        params=params,
    )
#+end_src
Then calling =handle(req)= produces a =Spectra= object produced by various calls to =read_spectra=, =stack=, etc.

The =test_*= functions (in testing.py) call the =handle= function to produce a Spectra, run basic sanity checks on its structure, and then return the Spectra object.
** Extra Context/Info
- We use objects =TargetParameters=, =TileParameters=, =RadecParameters= to store the parameters. They're just dataclasses wrapping the obvious fields.
- The =DESIROOT= is defined in =models.py=, it tries to read from the environment variable =$DESIROOT=
- You can also call any of the endpoint functions =tile, target, radec= with arguments directly, without going through =handle= (although this may break things if we add validation, etc. in =handle= which may happen)
* Running it as a webapp
Run =python3 webapp.py= and it should log what port it's running on with a message like =Running on http://127.0.0.1:5000=.

It works if you have your env vars (mainly =DESIROOT=) configured properly.

Make an API request via something like =<localhost>/api/v1/download/fuji/radec/RA,DEC,RADIUS_ARCSEC=.

It should give you back a FITS file, and also cache it somewhere under the =CACHE_DIR= defined in =models.py=.

If you access it from a browser you should get a pop-up asking if you want to download the file, if you access it from the terminal via =curl= or =wget= it should just give you the contents of the file (anecdotally, it may show up as unprintable characters in your terminal)

The cache dir is currently hardcoded to =$HOME/tmp/desi-api-cache=.
