# spectro_redux="/spectro_redux"
preload_releases = ["fujilite", "jura","iron"]
# Base dir where memmap, etc are stored
# zcatalog_dir TODO
[cache]
path= "~/tmp/desi-api-cache"
# How old must a cached response be before we discard it, in minutes
max_age = 0
# How large the cache is allowed to get
max_size = '1gb'
