FROM docker.io/library/python:3.11

#- install dependencies
RUN  python -m pip install --upgrade pip setuptools wheel \
  && python -m pip install astropy scipy numba "numpy<2.0" pytest fitsio "bokeh<3" flask numpyencoder \
  && python -m pip install --no-deps git+https://github.com/desihub/desiutil \
  && python -m pip install --no-deps git+https://github.com/desihub/desitarget \
  && python -m pip install --no-deps git+https://github.com/desihub/desispec \
  && python -m pip install --no-deps git+https://github.com/desihub/prospect \
  && python -m pip install --no-deps git+https://github.com/desihub/redrock

#- get the Redrock templates, plus an older template to support the fuji specprod
RUN mkdir -p /desi/spectro \
  && cd /desi \
  && git clone https://github.com/desihub/redrock-templates \
  && curl  https://raw.githubusercontent.com/desihub/redrock-templates/0.7.2/rrtemplate-qso.fits -o redrock-templates/rrtemplate-QSO.fits

#- when launching the container, mount an external directory to /desi/spectro/redux
ENV DESI_ROOT=/desi
ENV DESI_SPECTRO_REDUX=/desi/spectro/redux

ENV RR_TEMPLATE_DIR=/desi/redrock-templates

#- if there are problems with fitsio, notes from desi github test env
##  && python -m pip cache remove fitsio \
##  && python -m pip install --no-deps --force-reinstall --ignore-installed fitsio


