# Default config values for the DESI API


[cache]
path= "~/tmp/desi-api-cache"
# How old must a cached response be before we discard it, in minutes
max_age = 60
# How large the cache is allowed to get
max_size = '1gb'


[paths]
# Absolute, but ~ is allowed
sql = "~/desi-sql"
spectro_redux=""
